/*
 * Attachment document-extraction self-test — run: node attach_extract_test.mjs
 * Round-trips REAL files through the REAL extractor with zero fixtures: docwriters.mjs
 * (the app's own document generator) produces a DOCX and a PDF, and the client-side
 * extractor module (public/attach-extract.mjs, the code every phone runs) pulls the
 * text back out. Also proves the honest refusals: old .doc bytes, non-zip garbage,
 * image-only PDFs, and the truncation cap. Uses the vendored pdf.js, offline.
 */
import { markdownToDocx, markdownToPdf, rowsToXlsx, zipBuffer } from "./docwriters.mjs";
import { extractDocx, extractPdf, extractXlsx } from "./public/attach-extract.mjs";
import { pathToFileURL } from "node:url";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
let passed = 0, failed = 0;
const t = async (n, f) => { try { await f(); passed++; console.log("  ok  " + n); } catch (e) { failed++; console.error("FAIL  " + n + "\n      " + e.message); } };
const assert = (cond, msg) => { if (!cond) throw new Error(msg); };

// Load the vendored pdf.js exactly once (tests inject it; the browser path self-loads).
// Node has no Web Workers, so pdf.js falls back to its "fake worker": point workerSrc at
// the vendored worker file so that fallback can dynamically import it.
const pdfjs = await import(pathToFileURL(join(HERE, "public", "vendor", "pdfjs", "pdf.min.mjs")).href);
pdfjs.GlobalWorkerOptions.workerSrc = pathToFileURL(join(HERE, "public", "vendor", "pdfjs", "pdf.worker.min.mjs")).href;

const MD = `# Quarterly Coating Report

The Alpha crew completed **fourteen** roof sections in June.

- Elastomeric topcoat: 1.5 gallons per square
- Basecoat: DOMINION-MARKER-7742 applied at 2.0 gallons

| Section | Status |
| --- | --- |
| North wing | Complete |
| South wing | Pending |
`;

await t("DOCX round trip: generated by docwriters, extracted by the phone code", async () => {
  const buf = markdownToDocx(MD, "Quarterly Coating Report");
  const r = await extractDocx(new Uint8Array(buf));
  assert(r.text.includes("DOMINION-MARKER-7742"), "marker string missing from DOCX text");
  assert(r.text.includes("Quarterly Coating Report"), "title missing");
  assert(r.text.includes("North wing") && r.text.includes("Complete"), "table cell text missing");
  assert(!/<w:|<\/w:/.test(r.text), "raw XML leaked into the text");
});

await t("PDF round trip: generated by docwriters, extracted via vendored pdf.js", async () => {
  const buf = markdownToPdf(MD, "Quarterly Coating Report");
  const r = await extractPdf(new Uint8Array(buf), pdfjs);
  assert(r.text.includes("DOMINION-MARKER-7742"), "marker string missing from PDF text");
  assert(r.text.includes("[Page 1 of"), "page marker missing");
  assert(r.pages >= 1, "page count missing");
});

await t("old .doc bytes refuse with the save-as-.docx message", async () => {
  const ole = Buffer.concat([Buffer.from([0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1]), Buffer.alloc(600)]);
  let msg = "";
  try { await extractDocx(new Uint8Array(ole)); } catch (e) { msg = e.message; }
  assert(/old \.doc format/.test(msg), "expected the old-.doc refusal, got: " + msg);
});

await t("non-zip garbage refuses honestly", async () => {
  let msg = "";
  try { await extractDocx(new TextEncoder().encode("this is not a word document at all")); } catch (e) { msg = e.message; }
  assert(/not a \.docx/.test(msg), "expected not-a-docx refusal, got: " + msg);
});

await t("image-only/empty PDF refuses as scanned instead of feeding the model nothing", async () => {
  // A structurally valid one-page PDF with NO text operators (what a scan looks like).
  const empty = Buffer.from(
    "%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n" +
    "3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj\nxref\n0 4\n0000000000 65535 f \n" +
    "0000000009 00000 n \n0000000052 00000 n \n0000000101 00000 n \ntrailer<</Size 4/Root 1 0 R>>\nstartxref\n164\n%%EOF");
  let msg = "";
  try { await extractPdf(new Uint8Array(empty), pdfjs); } catch (e) { msg = e.message; }
  assert(/scanned or image-only/.test(msg), "expected the scanned-PDF refusal, got: " + msg);
});

await t("truncation cap holds on a long document", async () => {
  const big = "Lorem ipsum dolor sit amet. ".repeat(3000);   // ~84KB of text
  const buf = markdownToDocx(big, "Big");
  const r = await extractDocx(new Uint8Array(buf), { maxChars: 5000 });
  assert(r.text.length <= 5000, "cap exceeded: " + r.text.length);
  assert(r.truncated === true, "truncated flag should be set");
});

await t("XLSX round trip: generated by docwriters (inline strings + numbers)", async () => {
  const buf = rowsToXlsx([["Job", "Squares", "Rate"], ["Truline North", 42, 1.5], ["MARKER-XL-3377", 7, 2.25]]);
  const r = await extractXlsx(new Uint8Array(buf));
  assert(r.text.includes("[Sheet: Sheet1]"), "sheet header missing");
  assert(r.text.includes("MARKER-XL-3377"), "inline string cell missing");
  assert(/Truline North\t42\t1\.5/.test(r.text), "row should be tab-separated with numbers intact");
});

await t("XLSX real-Excel shapes: shared strings + date cells convert to ISO", async () => {
  // Hand-built minimal workbook the way Excel writes it: sharedStrings + a date-styled cell.
  // Serial 46203 in the 1900 system = 2026-06-30 (anchor: 46023 = 2026-01-01, +180 days).
  // Style s=1 -> numFmtId 14 (a builtin date).
  const wb = zipBuffer([
    { name: "[Content_Types].xml", data: '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/></Types>' },
    { name: "_rels/.rels", data: '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>' },
    { name: "xl/workbook.xml", data: '<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Invoices" sheetId="1" r:id="rId1"/></sheets></workbook>' },
    { name: "xl/_rels/workbook.xml.rels", data: '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>' },
    { name: "xl/sharedStrings.xml", data: '<?xml version="1.0"?><sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="2" uniqueCount="2"><si><t>Client</t></si><si><r><t>Rich </t></r><r><t>Runs Inc</t></r></si></sst>' },
    { name: "xl/styles.xml", data: '<?xml version="1.0"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><cellXfs count="2"><xf numFmtId="0"/><xf numFmtId="14" applyNumberFormat="1"/></cellXfs></styleSheet>' },
    { name: "xl/worksheets/sheet1.xml", data: '<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c></row><row r="2"><c r="A2" s="1"><v>46203</v></c><c r="B2" t="b"><v>1</v></c></row></sheetData></worksheet>' },
  ]);
  const r = await extractXlsx(new Uint8Array(wb));
  assert(r.text.includes("[Sheet: Invoices]"), "sheet name missing");
  assert(r.text.includes("Client") && r.text.includes("Rich Runs Inc"), "shared/rich strings missing: " + r.text);
  assert(r.text.includes("2026-06-30"), "date serial 46203 should become 2026-06-30, got: " + r.text);
  assert(r.text.includes("TRUE"), "boolean cell missing");
});

await t("old .xls bytes refuse with the save-as-.xlsx message", async () => {
  const ole = Buffer.concat([Buffer.from([0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1]), Buffer.alloc(600)]);
  let msg = "";
  try { await extractXlsx(new Uint8Array(ole)); } catch (e) { msg = e.message; }
  assert(/old \.xls format/.test(msg), "expected the old-.xls refusal, got: " + msg);
});

console.log(`\nattach_extract_test: ${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
