/*
 * Attachment document-extraction self-test — run: node attach_extract_test.mjs
 * Round-trips REAL files through the REAL extractor with zero fixtures: docwriters.mjs
 * (the app's own document generator) produces a DOCX and a PDF, and the client-side
 * extractor module (public/attach-extract.mjs, the code every phone runs) pulls the
 * text back out. Also proves the honest refusals: old .doc bytes, non-zip garbage,
 * image-only PDFs, and the truncation cap. Uses the vendored pdf.js, offline.
 */
import { markdownToDocx, markdownToPdf } from "./docwriters.mjs";
import { extractDocx, extractPdf } from "./public/attach-extract.mjs";
import { pathToFileURL } from "node:url";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
let passed = 0, failed = 0;
const t = async (n, f) => { try { await f(); passed++; console.log("  ok  " + n); } catch (e) { failed++; console.error("FAIL  " + n + "\n      " + e.message); } };
const assert = (cond, msg) => { if (!cond) throw new Error(msg); };

// Load the vendored pdf.js exactly once (tests inject it; the browser path self-loads).
// Node has no Web Workers, so pdf.js falls back to its "fake worker": point workerSrc at
// the vendored worker file so that fallback can dynamically import it.
const pdfjs = await import(pathToFileURL(join(HERE, "public", "vendor", "pdfjs", "pdf.min.mjs")).href);
pdfjs.GlobalWorkerOptions.workerSrc = pathToFileURL(join(HERE, "public", "vendor", "pdfjs", "pdf.worker.min.mjs")).href;

const MD = `# Quarterly Coating Report

The Alpha crew completed **fourteen** roof sections in June.

- Elastomeric topcoat: 1.5 gallons per square
- Basecoat: DOMINION-MARKER-7742 applied at 2.0 gallons

| Section | Status |
| --- | --- |
| North wing | Complete |
| South wing | Pending |
`;

await t("DOCX round trip: generated by docwriters, extracted by the phone code", async () => {
  const buf = markdownToDocx(MD, "Quarterly Coating Report");
  const r = await extractDocx(new Uint8Array(buf));
  assert(r.text.includes("DOMINION-MARKER-7742"), "marker string missing from DOCX text");
  assert(r.text.includes("Quarterly Coating Report"), "title missing");
  assert(r.text.includes("North wing") && r.text.includes("Complete"), "table cell text missing");
  assert(!/<w:|<\/w:/.test(r.text), "raw XML leaked into the text");
});

await t("PDF round trip: generated by docwriters, extracted via vendored pdf.js", async () => {
  const buf = markdownToPdf(MD, "Quarterly Coating Report");
  const r = await extractPdf(new Uint8Array(buf), pdfjs);
  assert(r.text.includes("DOMINION-MARKER-7742"), "marker string missing from PDF text");
  assert(r.text.includes("[Page 1 of"), "page marker missing");
  assert(r.pages >= 1, "page count missing");
});

await t("old .doc bytes refuse with the save-as-.docx message", async () => {
  const ole = Buffer.concat([Buffer.from([0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1]), Buffer.alloc(600)]);
  let msg = "";
  try { await extractDocx(new Uint8Array(ole)); } catch (e) { msg = e.message; }
  assert(/old \.doc format/.test(msg), "expected the old-.doc refusal, got: " + msg);
});

await t("non-zip garbage refuses honestly", async () => {
  let msg = "";
  try { await extractDocx(new TextEncoder().encode("this is not a word document at all")); } catch (e) { msg = e.message; }
  assert(/not a \.docx/.test(msg), "expected not-a-docx refusal, got: " + msg);
});

await t("image-only/empty PDF refuses as scanned instead of feeding the model nothing", async () => {
  // A structurally valid one-page PDF with NO text operators (what a scan looks like).
  const empty = Buffer.from(
    "%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n" +
    "3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj\nxref\n0 4\n0000000000 65535 f \n" +
    "0000000009 00000 n \n0000000052 00000 n \n0000000101 00000 n \ntrailer<</Size 4/Root 1 0 R>>\nstartxref\n164\n%%EOF");
  let msg = "";
  try { await extractPdf(new Uint8Array(empty), pdfjs); } catch (e) { msg = e.message; }
  assert(/scanned or image-only/.test(msg), "expected the scanned-PDF refusal, got: " + msg);
});

await t("truncation cap holds on a long document", async () => {
  const big = "Lorem ipsum dolor sit amet. ".repeat(3000);   // ~84KB of text
  const buf = markdownToDocx(big, "Big");
  const r = await extractDocx(new Uint8Array(buf), { maxChars: 5000 });
  assert(r.text.length <= 5000, "cap exceeded: " + r.text.length);
  assert(r.truncated === true, "truncated flag should be set");
});

console.log(`\nattach_extract_test: ${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
